### ISSUE TITLE
Sharing/deleting don't work with swipe-to-open camera roll

### ISSUE THREAD

**Issue by MikeBeas** [kb1ooo/snappy-public#17]
When you swipe right to open the camera roll, then tap either the delete button or the share button, no UIActionSheet comes up to ask you to confirm/share. The screen fades like it's going to, but it just never does.

**Comment by kb1ooo** [comment]
On Sun, Jan 01, 2012 at 06:39:56PM -0800, MikeBeas wrote:

> When you swipe right to open the camera roll, then tap either the delete button or the share button, no UIActionSheet comes up to ask you to confirm/share. The screen fades like it's going to, but it just never does.

I'm not sure what you mean by "swipe right"?  I have tried from lock
screen, unlock icon view, and from within an app but I'm unable to
replicate the behavior.  Can you give me some steps to reproduce?

Thanks,
Marc

**Comment by MikeBeas** [comment]
When you're in the camera app (or in this case, Snappy), and you've just taken a photo, there are two ways to get to the camera roll. One is to tap the preview image in the corner (the "normal way") and the other is a new way introduced in iOS 5, which is to swipe from left to right like you're scrolling backwards through photos.

Mike Beasley

**Comment by kb1ooo** [comment]
Thanks.  Didn't catch that feature.  Working on it. 

Best,
Marc

**Comment by kb1ooo** [comment]
Ok so this a problem when launching snappy while unlocked.  It's showing
the action sheet underneath the view.  It looks non-trivial and I'd like
to get an official version out.  I'm going to disable it for Snappy
while unlocked and then add this as a feature request if that's ok.

**Comment by MikeBeas** [comment]
sure, that's fine

**Comment by kb1ooo** [comment]
Disabled swipe to camera-roll from unlocked access in 3.0-rc1.  Adding as feature request.
