### ISSUE TITLE
Snappy can open inside itself

### ISSUE THREAD

**Issue by MikeBeas** [kb1ooo/snappy-public#18]
I have Snappy set to open when I double-tap my status bar. When I'm in Snappy, I can open the camera roll, double-tap the status bar and open another instance of Snappy inside my existing instance. Then the home button doesn't get me anywhere at all. I can keep doing this as many times as I want and there is no way out except to lock and then unlock the device or respring.

**Comment by kb1ooo** [comment]
Fixed 3.0-rc1
