### ISSUE TITLE
Snappy gets stuck open

### ISSUE THREAD

**Issue by MikeBeas** [kb1ooo/snappy-public#24]
Reproduce:
1) Open Snappy while in an app
2) Open the camera roll
3) While the camera roll is opening, press the home button (also works while the camera roll is closing)

Expected:
Snappy closes

Actual:
Snappy stays open and the app behind it closes. Snappy gets stuck open on the Springboard. If you press the home button, the Spotlight keyboard comes up, but Snappy stays in the front. You can open the task switcher and open an app without any issue, but when you quit the app Snappy will still be sitting on the Springboard until you respring.

**Comment by kb1ooo** [comment]
On Tue, Jan 10, 2012 at 10:30:24PM -0800, Mike Beasley wrote:

> Reproduce:
> 1) Open Snappy while in an app
> 2) Open the camera roll
> 3) While the camera roll is opening, press the home button (also works while the camera roll is closing)
> 
> Expected:
> Snappy closes
> 
> Actual:
> Snappy stays open and the app behind it closes. Snappy gets stuck open
> on the Springboard. If you press the home button, the Spotlight
> keyboard comes up, but Snappy stays in the front. You can open the
> task switcher and open an app without any issue, but when you quit the
> app Snappy will still be sitting on the Springboard until you
> respring.

Thanks Mike, I was able to reproduce.

**Comment by ymoran00** [comment]
To me it gets stuck also if I start it from lock state. The behavior is the same - stuck on camera, and Home simply opens the keyboard. It means I need to resorting all the time...
