### ISSUE TITLE
Unable to access photos etc.

### ISSUE THREAD

**Issue by padmavyuha** [kb1ooo/snappy-public#4]
Snappy 3.0-b-1 won't give me access to my photos etc. when I slide out of camera view mode - it thinks I'm still at the lock screen though the phone is unlocked.

[irrelevant screencap deleted]

Okay, well I should have checked that screencap before posting it - turns out you can't screencap whilst in Snappy :). The screen I was trying to cap says:

Your iPhone is locked.
Unlock your iPhone to see all of your photos and videos.

**Comment by kb1ooo** [comment]
Thanks,

I'm labeling as a major bug b/c it breaks native app as well.  Fix will appear in next update. 

Marc

**Comment by padmavyuha** [comment]
Look forward to it - it's really nice to have Snappy back again, thanks for the hard work.
- Padma
