### ISSUE TITLE
11 feature requests (and some bug fixes)

### ISSUE THREAD

**Issue by AltF5** [kb1ooo/snappy-public#7]
1. Preserve previous on-screen options in Snappy
   I cannot explain enough how many times I have gotten bitten by thinking the flash is off because I turned it off in the previous Snappy pulldown, but when the new snappy window appears, all options are reset (meaning the flash goes back to Auto, and causes it to go off when taking a picture in a situation when this is not desired)
   Usefulness/Priority: Very High
2. Bug/Annoyance fix needed: Allow snappy to display the previous photo taken, when clicking on the preview button
   50% of the time Snappy will NOT display the previous photo taken, but rather the photo before it, making you think the picture never even took. This bug definitely needs to be fixed.
   Usefulness/Priority: Very High
3. Provide a setting to enable or disable the preview
   Usefulness/Priority: Moderate
4. Provide a setting to enable or disable the pulldown animation
   When enabled: Have snappy simply appear (instead of being dropped down from the top)
   Usefulness/Priority: Low
5. Annoyance fix: When Snappy is activated on the lockscreen, prevent the OS from turning off the backlight (like what BiteSMS does when composing a new message, or replying via Quick Reply)
   This bug is annoying because if Snappy is pulled down on the lockscreen, then when the lockscreen's backlight dim/turn off timeout expires, then snappy disappears ...which in turn forces me to never use it on the lockscreen if I know it will be open for a while.
   Usefulness/Priority: High
6. Add a setting to show a grid layout (See: Camera+ application in the App Store)
   Usefulness/Priority: Low
7. Add a setting to tap on the screen to have the picture taken (See: Camera Plus Pro in the App Store)
   Usefulness/Priority: Moderate
8. Add a 4th option to the onscreen option for flash, to have the LED light remain on, so that the camera can focus on an option if it is dark (See: Camera+ aplication in the App Store)
   Usefulness/Priority: Moderate
9. Add a setting to highlight all onscreen options in blue (or some other color to callout their current state)
   This is good in low light situations when I cannot see the onscreen settings to save my life
   Usefulness/Priority: High
10. Annoyance fix:
    Whenever snappy is shown, at the very top of the screen, there is a line of pixels that span across the entire width of the LCD which shows the screen behind the snappy window
    (Ex: the wallpaper on the SB, the background for the application, etc)
    This is just a distraction, and shows that the application isn't polished
    Usefulness/Priority: Moderate
11. Add an setting to allow the Snappy to take photos with the Home button.
    This would require a new onscreen option to be displayed to close snappy.
    This is not only useful to have another physical button to take the photo, but also to have snappy remain down for as long as needed, without accidentally hitting the home button.
    Usefulness/Priority: Moderate

**Comment by kb1ooo** [comment]
Some of these issues are <3.0 related and therefore NA as I am no longer continuing development on Snappy for 4.x versions of iOS.  If you can revise these issues/features based on the new beta, and break out into separate issues, that would be great.

Thanks,
Marc
kb1ooo

**Comment by AltF5** [comment]
Everything bug related is fixed in this beta. Great job!
The only thing that applies from this list is just additional enhancements/feature requests. These are:
3, 4, 7, 8, 9, 11

Would u want each broken out into a separate "issue"? (not really issues, but simply features to work on in the future, or put on your ToDo list)

**Comment by kb1ooo** [comment]
I went ahead and broke the remaining ones out.  Going to close this composite one.  I've made them low priority until I get other requests.

Thanks,
Marc

**Comment by AltF5** [comment]
Excellent. Thank you very much :-)

On Friday, December 30, 2011, Marc Vaillant <
reply@reply.github.com>
wrote:
